---
development:
  cloud_name: dpqvjewsl
  api_key: '444931133313317'
  api_secret: UVSBF2OS1h-6eZiIEmqr4BlFuPs
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dpqvjewsl
  api_key: '444931133313317'
  api_secret: UVSBF2OS1h-6eZiIEmqr4BlFuPs
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dpqvjewsl
  api_key: '444931133313317'
  api_secret: UVSBF2OS1h-6eZiIEmqr4BlFuPs
  enhance_image_tag: true
  static_file_support: false
